### ISSUE TITLE
Social icons not showing up

### ISSUE THREAD

**Issue by sagarmrey** [BlackrockDigital/startbootstrap-freelancer#42] opened 2015-06-04 08:56 UTC
![screenshot-ironsummitmedia](https://cloud.githubusercontent.com/assets/8036205/7980486/8cdec414-0ac5-11e5-8560-206e305cb55d.jpg)
The social icons under the 'Around the web' are not opening.

**Comment by toubou91** [comment] 2015-08-27 09:26
I can verify that I reproduced this issue in the past, but I wasn't able to find a workaround for this.
Seemed like it was a browser issue for me (Chrome), but I'm not facing it any more.

Nevertheless, it would be great if someone provided an explanation of this attitude :) .

**Comment by Wferr** [comment] 2015-08-29 05:09
Could be happening because of a adblock  like extension?

**Comment by bencomeau** [comment] 2015-09-02 01:12
@Wferr Yes, it's likely that. See this thread below regarding the issue via Font Awesome who generates the icons used in the theme.

https://github.com/FortAwesome/Font-Awesome/issues/1799

**Comment by MichaelPehl** [comment] 2015-09-15 10:27
Your "error" has nothing to do with this theme itself.

**Comment by potherca** [comment] 2015-09-30 18:02
Could be easily resolved by implementing the workaround suggested in the issue that is linked above:

> To work around this, you'll need to modify the social icon class names.

**Comment by davidtmiller** [comment] 2016-07-01 17:36
These should be fixed now.

**Closed by davidtmiller** 2016-07-01 17:36 UTC
