### ISSUE TITLE
Icons not showing up on Firefox

### ISSUE THREAD

**Issue by FraV** [BlackrockDigital/startbootstrap-freelancer#219] opened 2019-07-29 16:33 UTC
Hello, I'm tryng to use Freelance template for a simple html project. The template works fine with Chrome and Edge (didn't try Safari yet), but Firefox appearently can't load the star icon in the divider and the "+" icon that should appear on the portfolio items when the mouse is over them. The issue is not caused by some editin on the code, since it also happens with the original template. I'm running Firefox Quantum 68.0.1, updated it a few days ago.
Could anyone please help me? I'm not super skilled, I just know some HTML and CSS, so please rmember this when answering.
Thank you very much!

![immagine](https://user-images.githubusercontent.com/36677513/62065391-27a76680-b22f-11e9-8d3e-f91733210e16.png)
![Screenshot (17)](https://user-images.githubusercontent.com/36677513/62065463-53c2e780-b22f-11e9-8694-2a3765181658.png)

**Comment by awalis** [comment] 2019-10-11 21:43
Hi, I experience almost the same problem over here with Firefox (60.9.0 ESR).

The star and the magnifier (what you called "+" sign)  icons are actually characters from ["Font Awesome"](https://fontawesome.com/) font family, corresponding to the codes ["\f005"](https://fontawesome.com/icons/star?style=solid) and ["\f00e"](https://fontawesome.com/icons/search-plus?style=solid) respectively. 

**What I did**
- installed Hugo 0.57.2
- added freelancer theme `git submodule add URL PATH`
- copied config.toml & projects/ from the example site
- tested it locally `hugo server -D`
- generated the website `hugo`
- uploaded files to the remote server via ftp

**What I expect** 
To see the same result on the remote server as I got with the local server, namely the star & magnifier icons.

**What I get**
In my case, with Firefox for GNU+Linux Desktop, I noticed two behaviors
1. on the **local server** at "localhost:1313" everything is well displayed, I can see the star and magnifier, behaving as intended. 
2. on the **remote server**, different characters are displayed instead of the two icons (as shown on the pictures).

**Workaround**
One work around would be to make images (.png) of the two icons and load them, instead of relying on the font package.  

**Origin of the problem**
I wonder if this has to do with freelancer theme, because I get the same odd display when I visit FontAwesome's website and search for these two icons.

**Image 1:** the magnifier icon is missing, and replaced by something else

![github-freelancer-magnifier-icon-missing-Screenshot_2019-10-11](https://user-images.githubusercontent.com/36451254/66686519-3cf93200-ec6f-11e9-863b-398ed5d3132c.png)

**Image 2:** the star icon is missing, and replaced by something else

![github-freelancer-star-icon-missing-Screenshot_2019-10-11](https://user-images.githubusercontent.com/36451254/66686521-3d91c880-ec6f-11e9-81b3-254cfd0fc3fb.png)

**Comment by davidtmiller** [comment] 2020-04-01 23:31
It looks like this was either an issue with Font Awesome or a previous version of the theme. I just tested in Firefox and it looks like the icons are working fine. I am thinking that this was fixed whenever Font Awesome was updated, possibly in the Font Awesome 5 update. Closing this since I don't see any problems in Firefox at the moment. If it's happening in Hugo, it would be a compatibility issue between Font Awesome and Hugo which would be outside the scope of this project.

**Closed by davidtmiller** 2020-04-01 23:32 UTC
